---
title: "Introduction"
execute:
  warning: false
  message: false
  eval: false
---

# How to use the materials?

This repository contains the teaching materials for the Single Cell Boot Camp - Analyzing scRNA-seq with R.

It has:

Two chapters of precourse preparation: Precourse Preparation - R / Theory

Nine chapters of the analysis workflow: Chapter 1 - 9

::: callout-important
We notice that students who go through the teaching materials and run the code on their local desktops will have a much better learning outcome.

As we are NOT going to cover the R programming but SOLELY focusing on the analysis workflow, this is particularly important for students who are not familiar with R. So, **please do block some time and try to digest the materials before attending the Boot Camp**.

If you are familiar with R, you can skip the **Precourse Preparation** and jump to **Chapter 1 - 9**.
:::

**For further information, suggestions and bug report, please contact: [biox_support_emea\@bd.com](biox_support_emea@bd.com)**

# Description

The Single Cell Boot Camp: Analysis of scRNA-seq with R is to provide an overview of the analysis of single-cell RNA-seq using R. It is designed for early-stage researchers who want to adopt single-cell analysis in their toolbox. The workshop consists of theory in presentation and application in hands-on practice.

The workshop starts with a fast-paced training session on the common workflow of single-cell RNA-seq analysis, then continues with sessions on the common workflow of scRNA-seq using bioinformatics packages like Seurat.

# Prerequisites

Each participant are expected to have:

1\. An introductory background in statistics, specifically in the below concepts: Median, log2 fold change, p-value, adjusted p-value, variance, PCA.

2\. Basic familiarity with R and tidyr package, specifically in the below functions: %\>% (pipe), filter, mutate, pivot_longer, pivot_wider, map, pmap, select, left_join.

*If you would like to learn on your own with publicly available resources:*\
[Chapter 1 - 4](https://moderndive.com/index.html) from MordernDive.\
\
*If you would like to participate in an instructor-led R course:*\
[R for Biologist](https://genomics.ed.ac.uk/services/r-biologists) from Edinburgh Genomics. For details, please contact Edinburgh Genomics.

# Expected outcome

By the end of the workshop, participants will be familiar with the following topics: Common workflow of single cell analysis (pre-processing, quality control, filtering, normalization, Clustering, Cell type annotation).

# Reference

The building of materials for the course references and relies on many excellent and well written public avaialbe materials.

-   Seurat <https://satijalab.org/seurat/>

-   Single Cell Best Practices: <https://www.sc-best-practices.org/preamble.html>

-   Orchestrating Single-Cell Analysis with Bioconductor: <https://bioconductor.org/books/release/OSCA/>

-   Mary Piper, Meeta Mistry, Jihe Liu, William Gammerdinger, & Radhika Khetani. (2022, January 6). hbctraining/scRNA-seq_online: scRNA-seq Lessons from HCBC (first release). Zenodo. <https://doi.org/10.5281/zenodo.5826256>

# Disclaimer

Recommendations given by representatives of BD in the context of the creation and setup of customer-specific applications and assays, the composition of antibody panels and suggestions for data analysis are provided in a diligent manner. However, the Customer acknowledges that (i) such recommendations should not be treated as a substitute for the Customer's own examination, (ii) BD does not make any promises nor guarantees that recommendations are accurate and complete and will meet the Customer's present or future needs or will produce positive or specific results and (iii) Customer remains solely responsible for validating and deciding on any such recommendations.

BD therefore accepts no liability whatsoever in connection with any such recommendation and/or any results generated on the basis of such recommendations and, to the fullest extent permitted by law, expressly disclaims any and all warranties and any liability in this respect. In particular, the Customer assumes sole responsibility for the validation, use, selection, and suitability of the recommendations for its needs and objectives.

# License

See the [LICENSE](LICENSE.html) file for license rights and limitations (MIT).
